resources:
  - name: test_action
    type: GitRepo
    configuration:
      gitProvider: hmitgangGithub
      path: hmitgang/test-action
      branches:
        include: ^{{gitBranch}}$
      buildOn:
        commit: true  # Optionally true, but won't show each commit's status in Github
        pullRequestCreate: true
      cancelPendingRunsOn:
        pullRequestUpdate: true  # Optional


pipelines:
  - name: harrisonmActionsTest
    steps:
      - name: step1
        type: Bash
        configuration:
          inputResources:
            - name: test_action
              trigger: true
        execution:
          onExecute:
            - cd $res_test_action_resourcePath
            - test -f file.txt
            - "false"
            - echo "this"
          onFailure:
            - echo "failed"
      - name: step2
        type: Bash
        configuration:
          inputSteps:
            - name: step1
              status:
                - success
                - failure
                - error
                - cancelled
                - skipped
                - unstable
                - timeout
        execution:
          onExecute:
            - echo "Hello world!"