on: [pull_request, create]

jobs:
  check_pipelines:
    runs-on: ubuntu-latest
    name: JFrog Pipelines
    steps:
      - name: Check JFrog Pipeline's status
        uses: jfrog/pipelines-github-action
        with:
          pipeline-name: "harrisonmActionsTest"
          RT_TOKEN: ${{ secrets.RT_TOKEN }}
          RT_URL: ${{ secrets.RT_URL }}
