on: [pull_request, create]

jobs:
  check_pipelines:
    runs-on: ubuntu-latest
    name: JFrog Pipelines
    steps:
      - name: Check out the private repo
        uses: actions/checkout@v2
        with:
          repository: "jfrog/pipelines-github-action"
          ref: 'v1.0'
          token: ${{ secrets.github_PAT }}

      - name: Check JFrog Pipeline's status
        uses: ./
        with:
          pipeline-name: "harrisonmActionsTest"
          RT_TOKEN: ${{ secrets.RT_TOKEN }}
          RT_URL: ${{ secrets.RT_URL }}
